tissue: 'Whole_Blood'

rasqual_vcf: '/home/t.cri.yliang/scratch/run-rasqual-results/bgz_rasqual_{tissue}.chr{chr_num}.vcf.gz'
gene_metainfo: '/home/t.cri.yliang/scratch/run-rasqual-results/snp_count.chr{chr_num}.txt'
trc_bin: '/home/t.cri.yliang/scratch/run-rasqual-results/trc.{tissue}.bin'
covar_bin: '/home/t.cri.yliang/scratch/run-rasqual-results/covar.{tissue}.bin'
offset_bin: '/home/t.cri.yliang/scratch/run-rasqual-results/sf.{tissue}.bin'
trc_txt: '/home/t.cri.yliang/scratch/run-rasqual-results/trc.{tissue}.txt'

cis_window_size: 1000000
nthread: 8
rasqual_exe: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/rasqual/bin/rasqual'
extra_rasqual_cmd: 
  - '--fix-delta'
  - '--fix-phi'

outdir: '/scratch/t.cri.yliang/run-rasqual-results/run_whole_blood'
